In [1]:
import numpy as np

In [2]:
## 1. Creating a 1D Array
arr1 = np.array([10, 20, 30, 40, 50])

print(arr1)

[10 20 30 40 50]


In [3]:
## 2. Creating a 2D Array
arr2 = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr2)

[[10 20 30]
 [40 50 60]]


In [4]:
## 3. Creating a 3D Array
arr3 = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
## 4. Checking Dimensions and Data Types
print("Dimension of arr1:", arr1.ndim)
print("Dimension of arr2:", arr2.ndim)
print("Dimension of arr3:", arr3.ndim)

print("\nShape of arr1:", arr1.shape)
print("Shape of arr2:", arr2.shape)
print("Shape of arr3:", arr3.shape)

print("\nData type of arr1:", arr1.dtype)

Dimension of arr1: 1
Dimension of arr2: 2
Dimension of arr3: 3

Shape of arr1: (5,)
Shape of arr2: (2, 3)
Shape of arr3: (2, 2, 2)

Data type of arr1: int64


In [6]:
## 5. Indexing
numbers = np.array([10, 20, 30, 40, 50])

print("First element:", numbers[0])
print("Third element:", numbers[2])
print("Last element:", numbers[-1])

First element: 10
Third element: 30
Last element: 50


In [7]:
## 6. 2D Indexing
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Element at row 1, column 2:", matrix[0, 1])
print("Element at row 2, column 3:", matrix[1, 2])

Element at row 1, column 2: 20
Element at row 2, column 3: 60


In [8]:
## 7. Slicing
numbers = np.array([10, 20, 30, 40, 50, 60])

print("First three elements:", numbers[:3])
print("Elements from index 2:", numbers[2:])
print("Every second element:", numbers[::2])

First three elements: [10 20 30]
Elements from index 2: [30 40 50 60]
Every second element: [10 30 50]


In [9]:
## 8. 2D Slicing
matrix = np.array([
    [1, 2, 3],
    [9, 5, 8],
    [7, 8, 4]
])

print("First two rows:")
print(matrix[:2])

print("\nFirst two columns:")
print(matrix[:, :2])

First two rows:
[[1 2 3]
 [9 5 8]]

First two columns:
[[1 2]
 [9 5]
 [7 8]]


In [10]:
## 9. Reshaping
arr = np.arange(1, 13)

print("Original array:")
print(arr)

new_arr = arr.reshape(3, 4)

print("\nAfter reshaping:")
print(new_arr)

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

After reshaping:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
## 10. Creating Arrays Using NumPy Functions
# zeros()
zero_array = np.zeros((2, 3))
print("Zeros:")
print(zero_array)

# ones()
one_array = np.ones((2, 3))
print("\nOnes:")
print(one_array)

# arange()
range_array = np.arange(1, 11)
print("\nArange:")
print(range_array)

# linspace()
line_array = np.linspace(0, 10, 5)
print("\nLinspace:")
print(line_array)

Zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Arange:
[ 1  2  3  4  5  6  7  8  9 10]

Linspace:
[ 0.   2.5  5.   7.5 10. ]


In [12]:
## 11. Mathematical Operations
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiplication: [ 10  40  90 160]
Division: [10. 10. 10. 10.]


In [13]:
## 12. Vectorized Operations
numbers = np.array([1, 2, 3, 4, 5])

print("Original:", numbers)
print("Adding 10:", numbers + 10)
print("Multiplying by 2:", numbers * 2)
print("Square:", numbers ** 2)

Original: [1 2 3 4 5]
Adding 10: [11 12 13 14 15]
Multiplying by 2: [ 2  4  6  8 10]
Square: [ 1  4  9 16 25]


In [14]:
## 13. Boolean Masking
marks = np.array([45, 67, 32, 89, 76, 55, 91])

print("Marks greater than 70:")
print(marks[marks > 70])

Marks greater than 70:
[89 76 91]


In [15]:
print("Marks below 50:")
print(marks[marks < 50])

Marks below 50:
[45 32]


In [16]:
## 14. Broadcasting
prices = np.array([100, 200, 300, 400])

new_prices = prices + 10

print("Original prices:")
print(prices)

print("\nAfter adding 10:")
print(new_prices)

Original prices:
[100 200 300 400]

After adding 10:
[110 210 310 410]


In [17]:
## 15. Broadcasting with 2D Array
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

values = np.array([10, 20, 30])

result = matrix + values

print(result)

[[11 22 33]
 [14 25 36]]


In [18]:
## 16. Aggregate Functions
numbers = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(numbers))
print("Mean:", np.mean(numbers))
print("Minimum:", np.min(numbers))
print("Maximum:", np.max(numbers))
print("Median:", np.median(numbers))

Sum: 150
Mean: 30.0
Minimum: 10
Maximum: 50
Median: 30.0


In [19]:
## 17. Small Practice Example - Student Marks
marks = np.array([78, 85, 62, 90, 74, 88, 95, 69])

print("Student marks:")
print(marks)

print("\nAverage marks:", np.mean(marks))
print("Highest marks:", np.max(marks))
print("Lowest marks:", np.min(marks))
print("Median marks:", np.median(marks))

print("\nStudents scoring above 75:")
print(marks[marks > 75])

Student marks:
[78 85 62 90 74 88 95 69]

Average marks: 80.125
Highest marks: 95
Lowest marks: 62
Median marks: 81.5

Students scoring above 75:
[78 85 90 88 95]
